name: 1 - hello - world

# trigger
on: workflow_dispatch 

# در این قسمت جاب ها مشخص میشوند
jobs:
    # نام جاب اول
    first-job:
    # روی چه سیستم عاملی اجرا شود
        runs-on: ubuntu-latest

        #مشخص کردن استپ ها 
        steps:
            - name: Print hello 
              run: echo "Hello World"
              
    second-job:
        runs-on: ubuntu-latest
        steps:
             - name: Print Hi to you
               run: echo "Hi to you" 

             - name: I will fail.
               run: exit 1

             - name: Say Goodbye
               run: echo "Goodbye"        
